name: Social Readme

on:
  schedule:
    #- cron: '0 16 * * *'
    - cron: '0 0/30 * * * ?'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: sun0225SUN/Social-Readme@main
        with:
          blog_rss_link: https://blog.csdn.net/weixin_63717396/rss/list?spm=1001.2014.3001.5494
          blog_limit: 5 # blog数量
          brain_rss_link: https://blog.csdn.net/weixin_63717396/rss/list?spm=1001.2014.3001.5494
          brain_limit: 5
          douban_name: zrq
          douban_limit: 5 # 豆瓣最新动态数量
          commit_message: Updated social rss by social-readme # commit说明
          
